name: Test Workflow
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: list files
        run: ls -la

      - name: execute shell script
        run: |
          chmod +x .github/asciiscripts.sh
          ./.github/asciiscripts.sh

  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: execute shell script
        run: |
          chmod +x .github/asciiscripts.sh
          ./.github/asciiscripts.sh

  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: execute shell script
        run: |
          chmod +x .github/asciiscripts.sh
          ./.github/asciiscripts.sh








