name: Test Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: list files
        run: ls -la

      - name: execute shell script
        run: |
          chmod +x .github/asciiscripts.sh
          ./.github/asciiscripts.sh
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: script-output
          path: dragon_output.txt
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: execute shell script
        run: |
          chmod +x .github/asciiscripts.sh
          ./.github/asciiscripts.sh
      - name: downlaod artifact
        uses: actions/download-artifact@v3
        with:
          name: script-output
          path: dragon_output.t

  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: execute shell script
        run: |
          chmod +x .github/asciiscripts.sh
          ./.github/asciiscripts.sh

      - name: downlaod artifact
        uses: actions/download-artifact@v3
        with:
          name: script-output







