name: Test Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Execute shell script and save output
        run: |
          chmod +x .github/asciiscripts.sh
          ./.github/asciiscripts.sh > dragon_output.txt
          echo "✅ dragon_output.txt created"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: dragon_output.txt

  dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: script-output
          path: artifacts

      - name: Verify artifact in dev
        run: |
          ls -la artifacts
          cat artifacts/dragon_output.txt

  prod:
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: script-output
          path: artifacts

      - name: Verify artifact in prod
        run: |
          ls -la artifacts
          cat artifacts/dragon_output.txt








